# Generated by Django 5.2.6 on 2025-09-10 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=10)),
                ('entity_id', models.IntegerField()),
                ('date', models.DateField()),
                ('closed', models.BooleanField(default=False)),
                ('start', models.CharField(blank=True, max_length=5, null=True)),
                ('end', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'date'], name='core_availa_entity__6a59c0_idx')],
                'unique_together': {('entity_type', 'entity_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ClinicHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
                ('start', models.CharField(max_length=5)),
                ('end', models.CharField(max_length=5)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='core.clinic')),
            ],
            options={
                'ordering': ('clinic_id', 'weekday', 'start'),
                'unique_together': {('clinic', 'weekday', 'start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='VetHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
                ('start', models.CharField(max_length=5)),
                ('end', models.CharField(max_length=5)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='core.vet')),
            ],
            options={
                'ordering': ('vet_id', 'weekday', 'start'),
                'unique_together': {('vet', 'weekday', 'start', 'end')},
            },
        ),
    ]
